# Generated by Django 2.2.11 on 2020-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200407_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='story_images'),
        ),
    ]
